CREATE TABLE ASSOCIATE (
    WAuthorID INT NOT NULL,
    WBookID INT NOT NULL,
    PRIMARY KEY (WAuthorID, WBookID),
    FOREIGN KEY (WAuthorID) REFERENCES AUTHOR(AuthorID),
    FOREIGN KEY (WBookID) REFERENCES BOOK(BookID)
);