-- INVENTORY Table
CREATE TABLE INVENTORY (
    InventoryID INT PRIMARY KEY,
    RestockThreshold INT NOT NULL,
    BookID INT NOT NULL,
    FOREIGN KEY (BookID) REFERENCES BOOK(BookID)
);

-- ASSIST Table
CREATE TABLE ASSIST (
    ACustomerID INT NOT NULL,
    AEmployeeID INT NOT NULL,
    PRIMARY KEY (ACustomerID, AEmployeeID),
    FOREIGN KEY (ACustomerID) REFERENCES CUSTOMER(CustomerID),
    FOREIGN KEY (AEmployeeID) REFERENCES EMPLOYEE(EmployeeID)
);

-- INCLUDE Table
CREATE TABLE INCLUDE (
    IOrderID INT NOT NULL,
    IBookID INT NOT NULL,
    BookPrice DECIMAL(10, 2) NOT NULL,
    BookQuantity INT NOT NULL,
    PRIMARY KEY (IOrderID, IBookID),
    FOREIGN KEY (IOrderID) REFERENCES [ORDER](OrderID),
    FOREIGN KEY (IBookID) REFERENCES BOOK(BookID)
);

-- ASSOCIATE Table
CREATE TABLE ASSOCIATE (
    WAuthorID INT NOT NULL,
    WBookID INT NOT NULL,
    PRIMARY KEY (WAuthorID, WBookID),
    FOREIGN KEY (WAuthorID) REFERENCES AUTHOR(AuthorID),
    FOREIGN KEY (WBookID) REFERENCES BOOK(BookID)
);

-- PROCESS Table
CREATE TABLE PROCESS (
    PEmployeeID INT NOT NULL,
    POrderID INT NOT NULL,
    PRIMARY KEY (PEmployeeID, POrderID),
    FOREIGN KEY (PEmployeeID) REFERENCES EMPLOYEE(EmployeeID),
    FOREIGN KEY (POrderID) REFERENCES [ORDER](OrderID)
);
