-- BOOK Table
CREATE TABLE BOOK (
    BookID INT PRIMARY KEY,
    Title VARCHAR(255),
    Price DECIMAL(10, 2)
);

-- CUSTOMER Table
CREATE TABLE CUSTOMER (
    CustomerID INT PRIMARY KEY,
    Name VARCHAR(100),
    Email VARCHAR(100)
);

-- EMPLOYEE Table
CREATE TABLE EMPLOYEE (
    EmployeeID INT PRIMARY KEY,
    Name VARCHAR(100),
    Role VARCHAR(50)
);

-- AUTHOR Table
CREATE TABLE AUTHOR (
    AuthorID INT PRIMARY KEY,
    Name VARCHAR(100)
);

-- ORDER_TABLE (was ORDER)
CREATE TABLE ORDER_TABLE (
    OrderID INT PRIMARY KEY,
    CustomerID INT,
    OrderDate DATE,
    FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID)
);

-- INVENTORY Table
CREATE TABLE INVENTORY (
    InventoryID INT PRIMARY KEY,
    RestockThreshold INT NOT NULL,
    BookID INT NOT NULL,
    FOREIGN KEY (BookID) REFERENCES BOOK(BookID)
);

-- ASSIST Table
CREATE TABLE ASSIST (
    ACustomerID INT NOT NULL,
    AEmployeeID INT NOT NULL,
    PRIMARY KEY (ACustomerID, AEmployeeID),
    FOREIGN KEY (ACustomerID) REFERENCES CUSTOMER(CustomerID),
    FOREIGN KEY (AEmployeeID) REFERENCES EMPLOYEE(EmployeeID)
);

-- INCLUDE_TABLE (was INCLUDE)
CREATE TABLE INCLUDE_TABLE (
    IOrderID INT NOT NULL,
    IBookID INT NOT NULL,
    BookPrice DECIMAL(10, 2) NOT NULL,
    BookQuantity INT NOT NULL,
    PRIMARY KEY (IOrderID, IBookID),
    FOREIGN KEY (IOrderID) REFERENCES ORDER_TABLE(OrderID),
    FOREIGN KEY (IBookID) REFERENCES BOOK(BookID)
);

-- ASSOCIATE Table
CREATE TABLE ASSOCIATE (
    WAuthorID INT NOT NULL,
    WBookID INT NOT NULL,
    PRIMARY KEY (WAuthorID, WBookID),
    FOREIGN KEY (WAuthorID) REFERENCES AUTHOR(AuthorID),
    FOREIGN KEY (WBookID) REFERENCES BOOK(BookID)
);

-- PROCESS Table
CREATE TABLE PROCESS (
    PEmployeeID INT NOT NULL,
    POrderID INT NOT NULL,
    PRIMARY KEY (PEmployeeID, POrderID),
    FOREIGN KEY (PEmployeeID) REFERENCES EMPLOYEE(EmployeeID),
    FOREIGN KEY (POrderID) REFERENCES ORDER_TABLE(OrderID)
);

