CREATE TABLE INCLUDE_TABLE (
    IOrderID INT NOT NULL,
    IBookID INT NOT NULL,
    BookPrice DECIMAL(10, 2) NOT NULL,
    BookQuantity INT NOT NULL,
    PRIMARY KEY (IOrderID, IBookID),
    FOREIGN KEY (IOrderID) REFERENCES ORDER_TABLE(OrderID),
    FOREIGN KEY (IBookID) REFERENCES BOOK(BookID)
);