CREATE TABLE PROCESS (
    PEmployeeID INT NOT NULL,
    POrderID INT NOT NULL,
    PRIMARY KEY (PEmployeeID, POrderID),
    FOREIGN KEY (PEmployeeID) REFERENCES EMPLOYEE(EmployeeID),
    FOREIGN KEY (POrderID) REFERENCES ORDER_TABLE(OrderID)
);